### ISSUE TITLE
add v_slab_compat

### ISSUE THREAD

**Issue by Skullians** [TheBonkedMinecraft/PackwizConfig#1]
add vertical slab compat (v_slab_compat) to packwiz ❤️ 

https://www.curseforge.com/minecraft/mc-mods/vertical-slabs-compat/files/4322500

(so neither of us forget KEKW)

**Comment by BhavyaSingh2611** [comment]
https://github.com/TheBonkedMinecraft/PackwizConfig/commit/71d43a8eb8ae1e181d052ac795952f5c6a5e7be9#diff-3eeda691f79d8b04217e80234cee199c0e35fc6d034cd842c8b7f16e6a6c520e

Added :tbmstrLoves:
